theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true

params:
  plausible: noscrollday.fr
  posts:
    index:
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid # grid | list
      options:
        hide_category: true